site_name: Jingbo Gao's Website
site_url: https://dylan-gao.github.io
nav:
    - Home: index.md
    - 主页: about_zh_cn.md
    - IC 小白的进阶之路: learning.md
theme: material
extra:
  analytics:
    provider: google
    property: G-MWWBG73GMV